sudo: required

language: python

python:
  - "3.4"

services:
  - docker

cache:
  - apt
  
env:
  - MONGO_IMAGE=mongo:3.2.7 DOCKER_OPTIONS="-e USE_MONGO_SERVER=1 -e WIDUKIND_MONGODB_URL=mongodb://mongodb/widukind_test?connectTimeoutMS=60000&serverSelectionTimeoutMS=60000 --link=mongodb:mongodb --rm"

before_install:
  - docker pull $MONGO_IMAGE
  - docker run --privileged -d --name=mongodb $MONGO_IMAGE mongod --noauth --storageEngine wiredTiger --wiredTigerDirectoryForIndexes
  - docker build -t widukind/common -f DockerfileTests .
  - pip install coveralls
 
before_script:
  - sleep 15
  - env
  - docker version
  - docker -D info
  - docker run $DOCKER_OPTIONS widukind/common pip freeze

script:
  - docker run $DOCKER_OPTIONS -e COVERAGE_FILE=/coverage/.coverage -v $PWD/coverage:/coverage widukind/common nosetests -x --with-coverage widukind_common
  - docker run $DOCKER_OPTIONS widukind/common flake8 --exit-zero widukind_common
  
after_script: COVERAGE_FILE=./coverage/.coverage coveralls --verbose

notifications:
  email: true
  on_success: always
  on_failure: always
