sudo: required

language: python

python:
  - "3.4"

services:
  - docker

cache:
  - apt
  
env:
  - MONGO_IMAGE=mongo:3.2.0 DOCKER_OPTIONS="-e WIDUKIND_MONGODB_URL=mongodb://mongodb/widukind_test --link=mongodb:mongodb --rm"

before_install:
  - docker pull $MONGO_IMAGE
  - docker run -d --name=mongodb $MONGO_IMAGE mongod --noauth
  - docker build -t widukind/common -f DockerfileTests .
  - pip install coveralls
 
before_script:
  - sleep 15
  - env
  - docker run $DOCKER_OPTIONS widukind/common pip freeze

script:
  - docker run $DOCKER_OPTIONS -e COVERAGE_FILE=/coverage/.coverage -v $PWD/coverage:/coverage widukind/common nosetests --with-coverage -s -v widukind_common
  - docker run $DOCKER_OPTIONS widukind/common flake8 --exit-zero widukind_common
  
after_script: COVERAGE_FILE=./coverage/.coverage coveralls --verbose

notifications:
  email: true
  on_success: always
  on_failure: always
